// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkEmrhuBZEL-WEopraSUvIARKmiSImrc4',
    appId: '1:767814630164:web:4a1405931d930e1fb56001',
    messagingSenderId: '767814630164',
    projectId: 'chat-app-8e2b8',
    authDomain: 'chat-app-8e2b8.firebaseapp.com',
    storageBucket: 'chat-app-8e2b8.appspot.com',
    measurementId: 'G-MXCPWBM5EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMGl6VJvGLJecD105JkwpeZVn2ZuazhU',
    appId: '1:767814630164:android:131b0cee4d00c8ddb56001',
    messagingSenderId: '767814630164',
    projectId: 'chat-app-8e2b8',
    storageBucket: 'chat-app-8e2b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwl6HMUjaohzRUihDs2wSkK9M1OJKqx_U',
    appId: '1:767814630164:ios:3a752c70055de9f2b56001',
    messagingSenderId: '767814630164',
    projectId: 'chat-app-8e2b8',
    storageBucket: 'chat-app-8e2b8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwl6HMUjaohzRUihDs2wSkK9M1OJKqx_U',
    appId: '1:767814630164:ios:5a2d90eae23e19cdb56001',
    messagingSenderId: '767814630164',
    projectId: 'chat-app-8e2b8',
    storageBucket: 'chat-app-8e2b8.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
